// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "em_golang_rest_service_example/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// CreateSubscription provides a mock function with given fields: subscription
func (_m *Creator) CreateSubscription(subscription model.SubscriptionSpec) (int64, error) {
	ret := _m.Called(subscription)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(model.SubscriptionSpec) (int64, error)); ok {
		return rf(subscription)
	}
	if rf, ok := ret.Get(0).(func(model.SubscriptionSpec) int64); ok {
		r0 = rf(subscription)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(model.SubscriptionSpec) error); ok {
		r1 = rf(subscription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator {
	mock := &Creator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
