// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "em_golang_rest_service_example/internal/model"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// FilteredDataReader is an autogenerated mock type for the FilteredDataReader type
type FilteredDataReader struct {
	mock.Mock
}

// FilterSubscriptions provides a mock function with given fields: startDate, endDate, userId, serviceName
func (_m *FilteredDataReader) FilterSubscriptions(startDate model.Date, endDate model.Date, userId uuid.UUID, serviceName *string) ([]model.Subscription, error) {
	ret := _m.Called(startDate, endDate, userId, serviceName)

	if len(ret) == 0 {
		panic("no return value specified for FilterSubscriptions")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Date, model.Date, uuid.UUID, *string) ([]model.Subscription, error)); ok {
		return rf(startDate, endDate, userId, serviceName)
	}
	if rf, ok := ret.Get(0).(func(model.Date, model.Date, uuid.UUID, *string) []model.Subscription); ok {
		r0 = rf(startDate, endDate, userId, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Date, model.Date, uuid.UUID, *string) error); ok {
		r1 = rf(startDate, endDate, userId, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFilteredDataReader creates a new instance of FilteredDataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilteredDataReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilteredDataReader {
	mock := &FilteredDataReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
