// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "em_golang_rest_service_example/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ListReader is an autogenerated mock type for the ListReader type
type ListReader struct {
	mock.Mock
}

// GetSubscriptions provides a mock function with given fields: limit, offset
func (_m *ListReader) GetSubscriptions(limit *int, offset *int) ([]model.Subscription, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptions")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(*int, *int) ([]model.Subscription, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(*int, *int) []model.Subscription); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(*int, *int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewListReader creates a new instance of ListReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListReader {
	mock := &ListReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
