// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "em_golang_rest_service_example/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// GetSubscription provides a mock function with given fields: id
func (_m *Reader) GetSubscription(id int64) (model.Subscription, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscription")
	}

	var r0 model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (model.Subscription, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) model.Subscription); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Subscription)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
