// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "em_golang_rest_service_example/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// Updater is an autogenerated mock type for the Updater type
type Updater struct {
	mock.Mock
}

// UpdateSubscription provides a mock function with given fields: id, newPrice, newEnd
func (_m *Updater) UpdateSubscription(id int64, newPrice int, newEnd model.Date) error {
	ret := _m.Called(id, newPrice, newEnd)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int, model.Date) error); ok {
		r0 = rf(id, newPrice, newEnd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater {
	mock := &Updater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
